### ISSUE TITLE
Can't fire on my server

### ISSUE THREAD

**Issue by b2zeldafreak** [jfd/wpilot#7]
I installed Node.js and ran the wpilot.js. Didn't change anything in the configuration. When I connect I can do everything but fire the gun. Any suggestions?

(on a fresh install Ubuntu 10.10)

**Comment by jfd** [comment]
What browser are you using?

**Comment by b2zeldafreak** [comment]
Chrome

**Comment by jfd** [comment]
Have you tried it in an other browser? I just want to clarify if we are talking about a browser issue or a server issue here.

**Comment by Truemedia** [comment]
I have the same issue on the 4 main browsers excluding internet explorer as I cannot test it on there due to using a mac. Looks like a server-side issue

**Comment by burakince** [comment]
I can't fire on my server too. Server side Ubuntu 11.04 Nodejs v0.4.11
Tested clients, 
- Ubuntu 11.04 (server side computer) Chromium 12.0.742.112 didn't fire, Firefox 6 didn't connect
- Ubuntu 10.04 (other computer) Chromium 12.0.742.112 didn't fire, Firefox 3.6.20 didn't display game screen

**Comment by kingcoyote** [comment]
I have the same problem, but I've noticed that it isn't that I can't shoot, but that the bullets are invisible.

**Comment by jfd** [comment]
Is there any errors in your firebug console? 

Can you see bullets on any of the online servers?

I havent tested this on nodejs > 0.2.6.

**Comment by kingcoyote** [comment]
I'm using Chrome, and pulled up the console and got this:

http://i.imgur.com/Xlngx.png

As I navigated around with the arrow keys, you got the stream of "free buffer ship_thrust" messages, but hitting spacebar only threw up the "5".

The online servers look fine. This issue is happening for everyone on my network that is connecting to this server. 

Also, I should add that the bullets are not only not rendering visually, but the audio is missing as well.

**Comment by kingcoyote** [comment]
I just downgraded from whatever is the current master head to v1.0 and the issue seems to have gone away. My client, along with the clients of everyone else trying it, now have proper firing animations.

**Comment by jfd** [comment]
Use v.1.1 and it should work

**Comment by kingcoyote** [comment]
That fixed it. Thanks a lot!
